server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:192.168.1.238}:3306/productdb
    username: developer
    password: Mysqlpassword123#
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

  application:
    name: PRODUCT_SERVICE
  config:
    import: configserver:http://localhost:9296

