server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

spring:
  kafka:
    bootstrap-servers: 192.168.1.240:9092

  datasource:
    url: jdbc:mysql://${DB_HOST:192.168.1.239}:3306/productdb
    username: ramanujam
    password: mysql1234#
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

  application:
    name: PRODUCT_SERVICE
  config:
    import: configserver:http://localhost:9296



management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus

  metrics:
      distribution:
        percentiles-histogram:
          http:
            server:
              requests: true

  observations:
    key-values:
      application:${spring.application.name}

  tracing:
        sampling:
          probability: 1.0

